# Generated by Django 6.1.1 on 2026-09-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubmission',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
